name: dropout
channels:
  - defaults
dependencies:
  - python=3.10
  - ipython
  - ipykernel
  - jupyter
  - pip
  - pip:
    - fastapi
    - mistralai
    - python-dotenv
    - python-dotenv 
    - mistralai